name: Deploy to Firebase
on:
  push:
    branches:
      - main  # Adjust this as necessary

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: npm install
      working-directory: ./  # Adjust if your npm context is different

    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting,functions  # Deploy both hosting and functions
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
